--ozone-platform=wayland
--lang=zh-CN
--ignore-gpu-blocklist
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiIgnoreDriverChecks
--disable-features=Dav1dVideoDecoder,BackForwardCache
--report-vp9-as-an-unsupported-mime-type
--process-per-site
--renderer-process-limit=4
--audio-buffer-size=2048
--disable-vulkan
--disk-cache-size=134217728
--media-cache-size=67108864
