--ozone-platform=wayland
--lang=zh-CN
--ignore-gpu-blocklist
--enable-features=AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks
--disable-features=Dav1dVideoDecoder
--report-vp9-as-an-unsupported-mime-type
--process-per-site
--audio-buffer-size=2048
